EVENT_ENTER_STUDY = "enter_study"
EVENT_LEAVE_STUDY = "leave_study"

EVENT_START_STUDY = "start_study"
EVENT_READING = "reading"
EVENT_WRITING = "writing"

EVENT_COMPUTER_USAGE = "computer_usage"
EVENT_PHONE_USAGE = "phone_usage"

EVENT_PICK_UP_PHONE = "pick_up_phone"
EVENT_PUT_DOWN_PHONE = "put_down_phone"

EVENT_SWITCH_TO_PHONE = "switch_to_phone"
EVENT_RETURN_TO_STUDY = "return_to_study"

EVENT_STUDY_INTERRUPTION = "study_interruption"

EVENT_LONG_PHONE_USAGE = "long_phone_usage"
EVENT_LONG_ABSENCE = "long_absence"

EVENT_COMPUTER_LEARNING = "computer_learning"


ALL_EVENTS = [
    EVENT_ENTER_STUDY,
    EVENT_LEAVE_STUDY,
    EVENT_START_STUDY,
    EVENT_READING,
    EVENT_WRITING,
    EVENT_COMPUTER_USAGE,
    EVENT_PHONE_USAGE,
    EVENT_PICK_UP_PHONE,
    EVENT_PUT_DOWN_PHONE,
    EVENT_SWITCH_TO_PHONE,
    EVENT_RETURN_TO_STUDY,
    EVENT_STUDY_INTERRUPTION,
    EVENT_LONG_PHONE_USAGE,
    EVENT_LONG_ABSENCE,
    EVENT_COMPUTER_LEARNING,
]