# 基础事件持续时间
ENTER_STUDY_DURATION = 1.0
LEAVE_STUDY_DURATION = 2.0

START_STUDY_DURATION = 3.0
READING_MIN_DURATION = 3.0
WRITING_MIN_DURATION = 2.0

COMPUTER_USAGE_MIN_DURATION = 3.0
PHONE_USAGE_MIN_DURATION = 2.0

PICK_UP_PHONE_WINDOW = 1.5
PUT_DOWN_PHONE_WINDOW = 1.5

# 状态转换
SWITCH_TO_PHONE_MIN_DURATION = 2.0
RETURN_TO_STUDY_MIN_DURATION = 2.0

# 高级事件
STUDY_INTERRUPTION_MIN_DURATION = 5.0
LONG_PHONE_USAGE_DURATION = 30.0
LONG_ABSENCE_DURATION = 30.0

COMPUTER_LEARNING_MIN_DURATION = 5.0